language: android
sudo: false
jdk: oraclejdk7
env:
  matrix:
  - ANDROID_TARGET=android-L  ANDROID_ABI=armeabi-v7a armeabi
android:
  components:
  - platform-tools
  - build-tools-23.0.1
  - android-L
  - extra
before_install:
- openssl aes-256-cbc -K $encrypted_d3d6449b1a56_key -iv $encrypted_d3d6449b1a56_iv
  -in dexter0218.jks.enc -out dexter0218.jks -d
- chmod +x gradlew
